//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'Security'
    public partial class Security
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'Security'
    {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'Security.Id'
        public int Id { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'Security.Id'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'Security.Username'
        public string Username { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'Security.Username'
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'Security.Password'
        public string Password { get; set; }
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'Security.Password'
    }
}
