//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignUp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProperty
    {
        public int Prop_ID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> NumOfBed { get; set; }
        public Nullable<decimal> NumOfBath { get; set; }
        public Nullable<int> NumOfGarage { get; set; }
        public decimal FloorSize { get; set; }
        public decimal Price { get; set; }
        public decimal PropertySize { get; set; }
        public string Category { get; set; }
        public decimal Monthly_Levy { get; set; }
        public decimal Monthly_Rate { get; set; }
        public string PriceTerm { get; set; }
        public Nullable<System.DateTime> OccupationDate { get; set; }
        public int Agent_ID { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
    }
}
